### ISSUE TITLE
Havig problems

### ISSUE THREAD

**Issue by eriksdev1** [Yeaseen/FileExplorer#1]
Hello, I'm having problems running your code, I get the error:

 . . . ProjectFE\src\sample\Controller.java:26:28
java: package sun.reflect.generics.tree is not visible
  (package sun.reflect.generics.tree is declared in module java.base, which does not export it)

Any help is much appreciated.

Best Regards

**Comment by Yeaseen** [comment]
Hello eriksdev1,

Thank you for upholding this issue.

This problem arises mainly because sun.* is an internal API and it is bound to a specific JRE/JDK (Sun in this case), limiting portability of this program. If you do some research on Sun you will get to know that _**some sun.reflect internal APIs are deprecated in JDK 9 and will be encapsulated or removed in a future release.**_

Using such internal APIs is highly demotivated now. 

Instead, you can use the following classes.
-  **_javafx.scene.control.TreeItem_**
-  **_javafx.scene.control.TreeView_** 

These are recommended by **_Oracle_** itself.

Hope the link given below will help you.

[Using JavaFX UI Controls: Tree View](https://docs.oracle.com/javafx/2/ui_controls/tree-view.htm)

Best wishes.

**Comment by eriksdev1** [comment]
Really Appreciate the reply, thank  you, adding those imports make the program work, by any chance do you know how could I implement drag and drop within this tree view so I can move/copy folders/files ? that would be really useful

Best Regards !
